books/urls.py
from django.urls import path
from . import views

app_name = "books"

urlpatterns = [
    path("", views.BooksIndexView.as_view(), name="index"),
    path("ajouter", views.add_a_book, name="add_a_book"),
    path("ajouter-a-la-main", views.manually_add_a_book, name="manually_add_a_book"),
    path("livre/<int:pk>/", views.BooksDetailView.as_view(), name="book_detail"),
]

libraro/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", TemplateView.as_view(template_name="index.html"), name="index"),
    path("livres/", include("books.urls")),
]

books/models.py
from django.db import models

# Create your models here.


class Book(models.Model):
    isbn = models.CharField(max_length=17, unique=True)
    title = models.CharField(max_length=400)
    authors = models.CharField(max_length=400)
    publisher = models.CharField(max_length=200, blank=True, null=True)
    cover = models.URLField(blank=True, null=True, max_length=400)
    year = models.CharField(max_length=4, blank=True, null=True)
    language = models.CharField(max_length=5, blank=True, null=True)

    def __str__(self):
        return self.title

books/forms.py
from django import forms
from django.urls import reverse
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from .models import Book


class IsbnForm(forms.Form):
    isbn = forms.CharField(max_length=17, required=True)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_action = reverse("books:add_a_book")
        self.helper.form_method = "post"

        self.helper.add_input(
            Submit(
                "submit",
                "Ajouter le livre",
                css_class="mt-3 mb-3 btn-warning",
            )
        )


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        exclude = ["id"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_action = reverse("books:manually_add_a_book")
        self.helper.form_method = "post"

        self.helper.add_input(
            Submit(
                "submit",
                "Ajouter le livre",
                css_class="mt-3 mb-3 btn-warning",
            )
        )

books/views.py
from django.shortcuts import render
from django.views import generic
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.db import IntegrityError
from .models import Book
from .forms import IsbnForm, BookForm
from isbnlib import *


# Create your views here.


class BooksIndexView(generic.ListView):
    model = Book


class BooksDetailView(generic.DetailView):
    model = Book


def add_a_book(request):
    form = IsbnForm(request.POST or None)
    context = {"form": form}
    template_name = "books/add_a_book.html"
    if request.method == "POST":
        if form.is_valid():
            isbn = form.cleaned_data["isbn"]
            if is_isbn10(isbn):
                isbn = to_isbn13(isbn)
            try:
                data = meta(isbn, service="wiki")
            except:
                data = meta(isbn)
            # make isbn-13 or whatever just isbn
            if "ISBN-13" in data:
                data["isbn"] = data["ISBN-13"]
                del data["ISBN-13"]
            # make keys lowercase
            data = {k.lower(): v for k, v in data.items()}
            print(data)
            if not data:
                messages.warning(request, "Livre non trouvé dans les bases ISBN.")
                return HttpResponseRedirect(reverse("books:add_a_book"))

            try:
                new_book = Book.objects.create(**data)
                messages.success(request, f"Livre {new_book.title} a été ajouté.")
            except IntegrityError:
                messages.warning(
                    request, f"Livre déjà présent dans la base de données."
                )
            return HttpResponseRedirect(reverse("books:add_a_book"))
    return render(request, template_name, context)


def manually_add_a_book(request):
    form = BookForm(request.POST or None)
    context = {"form": form}
    template_name = "books/manually_add_a_book.html"
    if request.method == "POST":
        if form.is_valid():
            new_book = form.save()
            messages.success(request, f"Livre {new_book.title} a été ajouté.")
            return HttpResponseRedirect(reverse("books:manually_add_a_book"))

    return render(request, template_name, context)

books/templates/books/add_a_book.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}Mes Livres{% endblock title %}
{% block content %}

<h1>Ajouter un livre</h1>

{% crispy form form.helper %}

{% endblock content %}

books/templates/books/book_detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}Livres - {{book.title}}{% endblock title %}
{% block content %}



<div class="card">
  <div class="card-body">
    <h5 class="card-title">{{book.title}}</h5>
    <img height="300" src="{{book.cover}}" alt="{{book.title}}">

    <h6 class="card-subtitle m-5 text-muted">{{book.authors.0}}</h6>
    <p class="card-text">Publié en {{book.year}}</p>

  </div>
</div>

{% endblock content %}

books/templates/books/book_list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}Mes Livres{% endblock title %}
{% block content %}

<h1>Liste des livres</h1>

<table class="table">
   <thead>
    <tr>
    <th>Titre</th>
    <th>Auteurs</th>
    <th>Éditeur</th>
    <th>Année</th>
    </tr>
  </thead>
  {% for book in book_list %}
  <tr>
    <td><a href="{% url 'books:book_detail' book.id %}">{{book.title}}</a></td>
    <td>{{book.authors}}</td>
    <td>{{book.publisher}}</td>
    <td>{{book.year}}</td>
  </tr>
  {% endfor %}
</table>


{% endblock content %}

books/templates/books/manually_add_a_book.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}Mes Livres{% endblock title %}
{% block content %}

<h1>Ajouter un livre à la main</h1>

{% crispy form form.helper %}

{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>

    <!-- boostrap CSS -->

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!--<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    -->
   <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    {% load static %}
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <title>{% block title %}{% endblock %}</title>
    <link rel="icon"
        href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>📚</text></svg>">

</head>

<body>
<header>
{% block navbar %}
<!--newnav-->
<ul class="nav nav-tabs">
  <li class="nav-item">
    <a class="nav-link active" href="/">Accueil</a>
  </li>
  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Livres</a>
    <div class="dropdown-menu">
        <a class="dropdown-item" href="{% url 'books:index' %}">Liste</a>
        <a class="dropdown-item" href="{% url 'books:add_a_book' %}">Ajouter un livre</a>
        <a class="dropdown-item" href="{% url 'books:manually_add_a_book' %}">Ajouter un livre à la main</a>
    </div>
  </li>

  <li class="nav-item">
      <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
  </li>
  {% if request.user.is_authenticated %}
  <li class="nav-item">
    <a class="nav-link" href="{% url 'admin:logout' %}">Déconnexion</a>
  </li>
  {% endif %}
</ul>

<!--end newnav-->
  {% endblock %}
  {% block subbar %}{% endblock subbar %}
  </header>
    <main role="main" class="container">

    {% block messages %}
        {% if messages %}
                {% for message in messages %}
                <div {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %} role="alert">{{ message }}</div>
                {% endfor %}

        {% endif %}
    {% endblock %}

        {% block content %}{% endblock %}

    </main>

    <!-- Footer -->

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

templates/index.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}Mes machins{% endblock title %}
{% block content %}
<h1>Index</h1>


{% endblock content %}